language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '/tmp/.m2/repository'
    - '/tmp/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - mhjang@nextree.io

deploy:
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    application: travel-club-app
    deployment_group: travel-club-group
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: namoosori-juniors/travel-club
      branch: master