language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '/tmp/.m2/repository'
    - '/tmp/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - mhjang@nextree.io

before_deploy:
  - zip -r travel-club *
  - mkdir -p deploy
  - mv travel-club.zip deploy/travel-club.zip

deploy:
  - provider: s3
    local_dir: deploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: travel-club-bucket
    key: travel-club.zip
    bundle_type: zip
    application: travel-club
    deployment_group: travel-club-group
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: namoosori-juniors/travel-club
      branch: master