language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '/tmp/.m2/repository'
    - '/tmp/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - mhjang@nextree.io
