version: "3"
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USERNAME=travelclub
      - MONGODB_PASSWORD=travelclub
      - MONGODB_DATABASE=travelclub
    volumes:
      - /data/db:/data/db
    container_name: "mongodb"
    ports:
      - 27017:27017
  app:
    image: travel-club-boot
    container_name: "travel-club-app"
    ports:
      - 80:9001
    links:
      - mongodb