version: "3"
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /data/db:/data/db
#      - ./initdb/:/docker-entrypoint-initdb.d/
    container_name: "mongodb"
    ports:
      - 27017:27017
  app:
    image: travel-club-boot
    ports:
      - 9001:9001
    links:
      - mongodb
    container_name: "travel-club-app"
