version: "3"
services:
  mongodb:
    image: mongo:3.2.4
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /data/db:/data/db
    container_name: "mongodb"
    ports:
      - 27017:27017
    command: --smallfiles
  app:
    image: travel-club-boot
    ports:
      - 9001:9001
    links:
      - mongodb