server:
  port: 8080

spring:
  application:
    name: travel-club
  profiles:
    active: local


---
server:
  port: 9001

spring:
  profiles: local
  cache:
    type: redis
  data:
    mongodb:
      authentication-database: travelclub
      host: mongodb
      port: 27017
      database: travelclub
      username: travelclub
      password: travelclub
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: 127.0.0.1
    port: 6379


---
server:
  port: 9001

spring:
  profiles: dev
  cache:
    type: redis
  data:
    mongodb:
      authentication-database: travelclub
      host: mongodb
      port: 27017
      database: travelclub
      username: travelclub
      password: travelclub
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: 127.0.0.1
    port: 6379
