server:
  port: 8080

spring:
  application:
    name: travel-club
  profiles:
    active: local


---
server:
  port: 9001

spring:
  profiles: local
  data:
    mongodb:
      authentication-database: travelclub
      host: mongodb
      port: 27017
      database: travelclub
      username: travelclub
      password: travelclub


---
server:
  port: 9001

spring:
  profiles: dev
  data:
    mongodb:
      authentication-database: travelclub
      host: mongodb
      port: 27017
      database: travelclub
      username: travelclub
      password: travelclub
