server:
  port: 8080

spring:
  application:
    name: travel-club
  profiles:
    active: local


---
spring:
  profiles: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/travelclub
    username: travelclub
    password: travelclub
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
